name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/kebun_v2/
          git pull origin main
          git status

          # Check if package.json or package-lock.json have changed
          if git diff --quiet HEAD~1 HEAD package.json package-lock.json; then
            echo "No changes in package.json or package-lock.json, skipping npm install"
          else
            echo "Changes detected in package.json or package-lock.json, running npm install"
            cd /var/www/kebun_v2/backend
            npm install
            cd ..
            cd /var/www/kebun_v2/frontend
            npm install
          fi
